# Generated by Django 4.2.14 on 2024-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_embeddingsfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbeddingsFile',
        ),
        migrations.AddField(
            model_name='paper',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
