# Generated by Django 4.2.14 on 2024-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_delete_embeddingsfile_paper_notes_alter_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
