# Generated by Django 4.2.14 on 2024-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_publication_date_paper_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
